### ISSUE TITLE
An example of usage

### ISSUE THREAD

**Issue by notcoffeetable** [iizukanao/node-rtsp-rtmp-server#1]
Hey,

I'm pretty excited about his project. I'm trying to get the server to work. Do you have an example of how you use it?

I'm looking to use this to host network rtsp video feeds. I understand currently it is supposed to get audio/video over a unix domain socket but I'm looking to expand it to TCP/UDP network sockets.

**Comment by GsandeepR** [comment]
Hi, I am sending feed from my App instead of ffmpeg.But I am  unable to play output.While debugging I got to know getStreamByRTSPUDPAddress is returning null .Even rtspUploadingClients has my App information ,why it is returning undefined.
![app](https://user-images.githubusercontent.com/16095573/30643057-20a9a056-9e2b-11e7-9f80-ef299c7f1c2e.png)
