### ISSUE TITLE
RPi Zero Takes more than 2 minutes to start

### ISSUE THREAD

**Issue by wikusjacobsz** [iizukanao/node-rtsp-rtmp-server#93]
Hi,

Why does the server take so long to start? More than 30 seconds on a RPi 3 and 130 seconds on a RPi Zero. Is there a way to reduce this time. Is the server waiting for something?

Thanx

**Comment by iizukanao** [comment]
@wikusjacobsz Compile *.coffee to *.js, then start the server with node command. This way, startup time will be much shorter.

```
$ cd node-rtsp-rtmp-server
$ coffee -c .
$ sudo node server.js
```

**Comment by wikusjacobsz** [comment]
@iizukanao Thank you for the suggestion. It seems like coffee compile worked. Noe errors and I have all the filas in a .js format as well.
But when I run the server it throws an error. Any suggestions? 

$ sudo node server.js
2017-10-01 14:02:29.597 attachRecordedDir: dir=file app=file
/home/pi/node-rtsp-rtmp-server/server.js:47
    throw err;
    ^

Error: bind EADDRINUSE 0.0.0.0:7044
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at _handle.lookup (dgram.js:242:18)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3

**Comment by wikusjacobsz** [comment]
Thank you so much for the help. Really appreciate it.

**Comment by Bodizappa** [comment]
I realize this issue is closed however I was trying to replicate the solution but I'm encountering some problems. When I issued the command:

`$ coffee -c .`

I get the following cryptic response:

`/home/pi/node-rtsp-rtmp-server/.AppleDouble/aac.coffee:1:69: error: unmatched }
��}	� 
����DEV�INO�SYN�SV~�"@�u"@�u�"@�u��t߭Z=
`
I've searched a bit for a solution to this but can't seem to figure it out. Any help would be greatly appreciated!
